$(document).ready(function(){
  $('.sidenav').sidenav();
});
$(document).ready(function(){
  $("#dugmeModal").click(function(){
      $("#testModal").modal('toggle');
  });
});
$('.slider').slider();